Repository svelte-society/sveltesociety.dev, pull requests merged in 2023-12, with the labels that each got.

#406 add svelte-selecto component
  src/routes/components/components.json
Labels: need rebase

#415 Added Vontigo
  src/routes/templates/templates.json
Labels: need rebase

#447 Add drab component library
  src/routes/components/components.json
Labels: need rebase

#435 add Svane component
  src/routes/components/components.json
Labels: need rebase

#434 Added Svault
  src/routes/components/components.json
Labels: need rebase

#195 Add `svelte-codesandbox`
  src/routes/components/components.json
Labels: stale, need rebase

#403 Add `curseur`
  src/routes/components/components.json
Labels: need rebase

#412 Add `@radar-azdelta/svelte-datatable`
  src/routes/components/components.json
Labels: need rebase

#354 Add Tablog
  src/routes/templates/templates.json
Labels: need rebase

#399 Added 3 new components
  src/routes/components/components.json
Labels: need rebase

#392 Add `chat-embed`
  src/routes/components/components.json
Labels: need rebase

#359 Add wails-template-sveltekit
  src/routes/templates/templates.json
Labels: need rebase

#197 Add `svelte-pin-input`
  src/routes/components/components.json
Labels: stale, need rebase

#340 Add `sveltekit-search-params`
  src/routes/components/components.json
Labels: need rebase, need formatting

#334 Add Skinny Pug starter template
  src/routes/templates/templates.json
Labels: need formatting

#387 Add `lucide-svelte`
  src/routes/components/components.json
Labels: need formatting

#351 Add SvelteKit with Prisma and AuthJS template
  src/routes/templates/templates.json
Labels: need rebase, need formatting

#227 Add walk-and-graph-svelte-components
  src/routes/tools/tools.json
Labels: stale
